version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/action/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    mode: '755'
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
      command: chmod +x /home/ec2-user/action/scripts/deploy.sh

  ApplicationStart:
    - location: /home/ec2-user/action/scripts/deploy.sh
      timeout: 60
      runas: ec2-user
