version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/action/  # 이 디렉토리 내에 배포가 진행된다
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh  #최상위 디렉토리의 script 폴더 내의 shell script가 실행된다.
      timeout: 60
      runas: ubuntu
